import { describe, expect, it } from 'vitest';
import {
  devig,
  devigAdditive,
  devigMultiplicative,
  devigPower,
  devigShin,
  devigWorstCase,
  overround,
} from '../src/engine/devig';
import type { DevigMethod } from '../src/config';

const MINUS_110 = 1 + 100 / 110;

const NORMALISED = {
  multiplicative: devigMultiplicative,
  additive: devigAdditive,
  power: devigPower,
  shin: devigShin,
} as const;

const METHOD_NAMES = Object.keys(NORMALISED) as Array<keyof typeof NORMALISED>;

function total(xs: number[]): number {
  return xs.reduce((a, b) => a + b, 0);
}

/** Deterministic PRNG (mulberry32) so the fuzz cases are identical on every run. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Random market: true probabilities from random weights, then a random margin applied multiplicatively. */
function randomMarket(rand: () => number, n: number): number[] {
  const w = Array.from({ length: n }, () => 0.2 + rand()); // max implied prob 0.857 × 1.15 < 1
  const s = total(w);
  const margin = 1 + rand() * 0.15;
  return w.map((x) => 1 / ((x / s) * margin));
}

describe('overround', () => {
  it('is Σ 1/d − 1', () => {
    // -110 implies 110/210 per side.
    expect(overround([MINUS_110, MINUS_110])).toBeCloseTo(220 / 210 - 1, 12);
    expect(overround([1.8, 2.1])).toBeCloseTo(65 / 63 - 1, 12);
    expect(overround([2, 2])).toBeCloseTo(0, 12);
    expect(overround([2.1, 2.1])).toBeLessThan(0);
  });
});

describe('worked examples', () => {
  it('-110 / -110 is 50/50 for every method', () => {
    for (const name of METHOD_NAMES) {
      const p = NORMALISED[name]([MINUS_110, MINUS_110]);
      expect(p[0], name).toBeCloseTo(0.5, 12);
      expect(p[1], name).toBeCloseTo(0.5, 12);
    }
    const w = devigWorstCase([MINUS_110, MINUS_110]);
    expect(w[0]).toBeCloseTo(0.5, 12);
    expect(w[1]).toBeCloseTo(0.5, 12);
  });

  it('1.80 / 2.10 multiplicative = 7/13, 6/13', () => {
    const p = devigMultiplicative([1.8, 2.1]);
    expect(p[0]).toBeCloseTo(7 / 13, 12);
    expect(p[1]).toBeCloseTo(6 / 13, 12);
  });

  it('1.80 / 2.10 additive removes the margin equally (34/63, 29/63)', () => {
    const p = devigAdditive([1.8, 2.1]);
    expect(p[0]).toBeCloseTo(34 / 63, 12);
    expect(p[1]).toBeCloseTo(29 / 63, 12);
  });

  it('two-way Shin coincides with additive (known closed-form result)', () => {
    for (const m of [
      [1.8, 2.1],
      [1.25, 4.5],
      [1.5, 2.7],
      [MINUS_110, 1.8],
    ]) {
      const s = devigShin(m);
      const a = devigAdditive(m);
      expect(s[0]).toBeCloseTo(a[0], 9);
      expect(s[1]).toBeCloseTo(a[1], 9);
    }
  });

  it('1.80 / 2.10 power: p_i = q_i^k with one common k and Σ q^k = 1', () => {
    const q = [1 / 1.8, 1 / 2.1];
    const p = devigPower([1.8, 2.1]);
    const k0 = Math.log(p[0]) / Math.log(q[0]);
    const k1 = Math.log(p[1]) / Math.log(q[1]);
    expect(k0).toBeGreaterThan(1);
    expect(k0).toBeCloseTo(k1, 9);
    expect(Math.pow(q[0], k0) + Math.pow(q[1], k0)).toBeCloseTo(1, 9);
    expect(p[0]).toBeCloseTo(0.540278, 6);
  });

  it('3-way soccer market (2.50 / 3.40 / 2.90)', () => {
    const m = [2.5, 3.4, 2.9];
    const q = m.map((d) => 1 / d);
    const b = total(q);
    const mult = devigMultiplicative(m);
    mult.forEach((p, i) => expect(p).toBeCloseTo(q[i] / b, 12));
    const add = devigAdditive(m);
    add.forEach((p, i) => expect(p).toBeCloseTo(q[i] - (b - 1) / 3, 12));
    for (const name of METHOD_NAMES) {
      const p = NORMALISED[name](m);
      expect(p).toHaveLength(3);
      expect(total(p), name).toBeCloseTo(1, 9);
      // Home is the favourite in every method.
      expect(p[0]).toBeGreaterThan(p[2]);
      expect(p[2]).toBeGreaterThan(p[1]);
    }
  });

  it('power recovers the true probabilities from a market generated by the power model', () => {
    const truth = [0.62, 0.25, 0.13];
    const k = 1.07;
    const decimals = truth.map((p) => 1 / Math.pow(p, 1 / k));
    const out = devigPower(decimals);
    out.forEach((p, i) => expect(p).toBeCloseTo(truth[i], 9));
  });

  it('Shin recovers the true probabilities from a market generated by the Shin model', () => {
    // Forward Shin model: π_i = S · sqrt(z p_i + (1 − z) p_i²), S = Σ_j sqrt(z p_j + (1 − z) p_j²).
    for (const [truth, z] of [
      [[0.7, 0.3], 0.03],
      [[0.45, 0.28, 0.27], 0.02],
      [[0.8, 0.15, 0.05], 0.05],
      [[0.4, 0.3, 0.2, 0.1], 0.01],
    ] as Array<[number[], number]>) {
      const r = truth.map((p) => Math.sqrt(z * p + (1 - z) * p * p));
      const s = total(r);
      const decimals = r.map((x) => 1 / (s * x));
      const out = devigShin(decimals);
      out.forEach((p, i) => expect(p).toBeCloseTo(truth[i], 9));
    }
  });
});

describe('favourite–longshot correction', () => {
  const markets = [
    [1.25, 4.5],
    [1.15, 6.5],
    [1.4, 3.2],
    [1.6, 2.6, 6.0],
    [1.3, 5.5, 9.0],
  ];

  it('power and Shin give the longshot less and the favourite more than multiplicative', () => {
    for (const m of markets) {
      const mult = devigMultiplicative(m);
      const fav = m.indexOf(Math.min(...m));
      const longshot = m.indexOf(Math.max(...m));
      for (const p of [devigPower(m), devigShin(m)]) {
        expect(p[longshot]).toBeLessThan(mult[longshot]);
        expect(p[fav]).toBeGreaterThan(mult[fav]);
      }
    }
  });
});

describe('invariants', () => {
  it('every normalised method sums to 1 and stays in (0,1) on fuzzed markets', () => {
    const rand = mulberry32(12345);
    for (let i = 0; i < 400; i++) {
      const n = [2, 2, 3, 4, 6][i % 5];
      const m = randomMarket(rand, n);
      for (const name of METHOD_NAMES) {
        const p = NORMALISED[name](m);
        expect(p).toHaveLength(n);
        expect(Math.abs(total(p) - 1), `${name} ${m.join(',')}`).toBeLessThanOrEqual(1e-9);
        for (const x of p) {
          expect(x).toBeGreaterThan(0);
          expect(x).toBeLessThan(1);
        }
      }
    }
  });

  it('extreme prices stay finite, in (0,1) and sum to 1', () => {
    for (const m of [
      [1.001, 800],
      [1.0001, 1.0001, 1000],
      [1.05, 10, 500],
      [1.01, 1.01],
      [50, 50, 50, 50, 1.02],
      [1 + 1e-9, 1e6],
    ]) {
      for (const name of METHOD_NAMES) {
        const p = NORMALISED[name](m);
        expect(Math.abs(total(p) - 1), `${name} ${m.join(',')}`).toBeLessThanOrEqual(1e-9);
        for (const x of p) {
          expect(Number.isFinite(x)).toBe(true);
          expect(x).toBeGreaterThan(0);
          expect(x).toBeLessThan(1);
        }
      }
    }
  });

  it('worst case is <= every method per outcome and sums to <= 1', () => {
    const rand = mulberry32(777);
    const cases = [[1.8, 2.1], [2.5, 3.4, 2.9], [1.25, 4.5], [1.05, 10, 500]];
    for (let i = 0; i < 100; i++) cases.push(randomMarket(rand, 2 + (i % 3)));
    for (const m of cases) {
      const w = devigWorstCase(m);
      for (const name of METHOD_NAMES) {
        const p = NORMALISED[name](m);
        p.forEach((x, j) => expect(w[j]).toBeLessThanOrEqual(x));
      }
      expect(total(w)).toBeLessThanOrEqual(1 + 1e-12);
      // It picks an actual method's value per outcome, never something lower.
      w.forEach((x, j) => {
        const candidates = METHOD_NAMES.map((name) => NORMALISED[name](m)[j]);
        expect(candidates).toContain(x);
      });
    }
  });

  it('worst case on 1.80/2.10 takes multiplicative for the favourite and power for the dog', () => {
    const w = devigWorstCase([1.8, 2.1]);
    expect(w[0]).toBeCloseTo(7 / 13, 12);
    expect(w[1]).toBeCloseTo(devigPower([1.8, 2.1])[1], 12);
    expect(total(w)).toBeLessThan(1);
  });

  it('does not mutate its input', () => {
    const m = [1.8, 2.1];
    devigWorstCase(m);
    expect(m).toEqual([1.8, 2.1]);
  });
});

describe('zero-margin input', () => {
  it('Σ1/d == 1 returns the multiplicative result for every method', () => {
    for (const m of [
      [2, 2],
      [1.5, 3],
      [4, 4, 2],
    ]) {
      const mult = devigMultiplicative(m);
      for (const name of METHOD_NAMES) {
        const p = NORMALISED[name](m);
        p.forEach((x, i) => expect(x).toBeCloseTo(mult[i], 12));
      }
      devigWorstCase(m).forEach((x, i) => expect(x).toBeCloseTo(mult[i], 12));
    }
    expect(devigMultiplicative([2, 2])).toEqual([0.5, 0.5]);
  });

  it('Σ1/d < 1 (an arb) is scaled up by the multiplicative method in every method', () => {
    const m = [2.2, 2.0];
    const mult = devigMultiplicative(m);
    expect(total(mult)).toBeCloseTo(1, 12);
    expect(mult[0]).toBeCloseTo(1 / 2.2 / (1 / 2.2 + 0.5), 12);
    for (const name of METHOD_NAMES) {
      const p = NORMALISED[name](m);
      p.forEach((x, i) => expect(x).toBeCloseTo(mult[i], 12));
    }
  });
});

describe('additive fallback', () => {
  it('falls back to multiplicative when a probability would go <= 0', () => {
    const m = [1.05, 10, 500]; // margin/3 exceeds the longshot's 0.2% implied probability
    expect(devigAdditive(m)).toEqual(devigMultiplicative(m));
  });
});

describe('devig dispatch', () => {
  it('routes to the named method', () => {
    const m = [2.5, 3.4, 2.9];
    expect(devig(m, 'multiplicative')).toEqual(devigMultiplicative(m));
    expect(devig(m, 'additive')).toEqual(devigAdditive(m));
    expect(devig(m, 'power')).toEqual(devigPower(m));
    expect(devig(m, 'shin')).toEqual(devigShin(m));
    expect(devig(m, 'worst')).toEqual(devigWorstCase(m));
  });

  it('rejects an unknown method', () => {
    expect(() => devig([2, 2], 'magic' as unknown as DevigMethod)).toThrow(RangeError);
  });
});

describe('input validation', () => {
  const bad: unknown[] = [
    [],
    [2],
    [1, 2],
    [0.5, 3],
    [-2, 2],
    [Number.NaN, 2],
    [Number.POSITIVE_INFINITY, 2],
    [2, '2'],
    null,
    undefined,
    'nope',
  ];

  it('throws RangeError for every function', () => {
    const fns = [overround, devigMultiplicative, devigAdditive, devigPower, devigShin, devigWorstCase];
    for (const input of bad) {
      for (const fn of fns) {
        expect(() => fn(input as number[]), `${fn.name}(${JSON.stringify(input)})`).toThrow(RangeError);
      }
      expect(() => devig(input as number[], 'worst')).toThrow(RangeError);
    }
  });
});
